package com.clipperai.product.entity;

public enum AuditAction {
	 	USER_SYNCED,
	 	USER_CREATED,
	 	USER_LOGIN,
	 
	 	AUTH_TOKEN_INVALID,
	    AUTH_TOKEN_MISSING,

	    CAMPAIGN_CREATED,
	    CAMPAIGN_UPDATED,
	    CAMPAIGN_DELETED,

	    SOURCE_VIDEO_REGISTERED,
	    SOURCE_VIDEO_DELETED,

	    VIDEO_JOB_CREATED,
	    VIDEO_JOB_STARTED,
	    VIDEO_JOB_COMPLETED,
	    VIDEO_JOB_FAILED,
	    VIDEO_JOB_CANCELED,
	    VIDEO_JOB_RETRIED,

	    CLIP_CANDIDATES_GENERATED,
	    COMPLIANCE_CHECK_COMPLETED,

	    RENDERED_CLIP_CREATED,
	    RENDERED_CLIP_DOWNLOADED,
	    
	    BILLING_CUSTOMER_CREATED,

	    SUBSCRIPTION_CREATED,
	    SUBSCRIPTION_UPDATED,
	    SUBSCRIPTION_UPGRADED,
	    SUBSCRIPTION_DOWNGRADED,
	    SUBSCRIPTION_CANCELED,
	    SUBSCRIPTION_REACTIVATED,
	    SUBSCRIPTION_PAYMENT_SUCCEEDED,
	    SUBSCRIPTION_PAYMENT_FAILED,
	    
	    PLAN_UPGRADE_STARTED,
	    PLAN_UPGRADE_PAYMENT_SUCCEEDED,
	    PLAN_UPGRADE_PAYMENT_FAILED,
	    PLAN_UPGRADE_APPLIED,
	    PLAN_UPGRADE_REFUNDED,
	    
	    EXTRA_CREDIT_PURCHASE_STARTED,
	    EXTRA_CREDIT_PURCHASE_SUCCEEDED,
	    EXTRA_CREDIT_PURCHASE_FAILED,
	    EXTRA_CREDIT_GRANTED,
	    EXTRA_CREDIT_CONSUMED,
	    EXTRA_CREDIT_REFUNDED,
	    
	    INVOICE_PAID,
	    INVOICE_PAYMENT_FAILED,
	    INVOICE_REFUNDED,
	    INVOICE_PARTIALLY_REFUNDED,
	    

	    REFUND_REQUESTED,
	    REFUND_APPROVED,
	    REFUND_REJECTED,
	    REFUND_CREATED,
	    REFUND_SUCCEEDED,
	    REFUND_FAILED,
	    
	    DISPUTE_CREATED,
	    DISPUTE_WON,
	    DISPUTE_LOST,
	    DISPUTE_CLOSED,
	    

	    USAGE_PERIOD_CREATED,
	    USAGE_LIMIT_REACHED,
	    USAGE_BLOCKED,
	    USAGE_INCREMENTED,

	    REFERRAL_CLICK_RECORDED,
	    AFFILIATE_ATTRIBUTION_CREATED,
	    COMMISSION_CREATED,
	    COMMISSION_APPROVED,
	    COMMISSION_REJECTED,
	    COMMISSION_PAID,
	    COMMISSION_CANCELED,
	    COMMISSION_REVERSED,

	    ADMIN_UPDATED_USER,
	    ADMIN_CANCELED_JOB,
	    ADMIN_ISSUED_REFUND,
	    ADMIN_ADJUSTED_CREDITS
}
