spring.datasource.url=jdbc:postgresql://localhost:5432/ai_clipper
spring.datasource.username=ai_clipper_user
spring.datasource.password=ai_clipper_password

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY}


spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.ai.openai.api-key=${OPENAI_API_KEY}

firebase.service-account-path=/home/mason/dev/clipperAi/clipperAiServer/fireBaseSecretCode.json

app.frontend-base-url=http://localhost:4200